on:
  push:
    branches: [ dev ]
name: Phpdark.com Deployment
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.IP }}
          ssh_private_key: ${{ secrets.PRIVATE }}
          local_path: './static/*'
          remote_path: '/var/www/demo/invoice-print-format'
          args: '-o ConnectTimeout=5'